spring.application.name=payment-processing-service
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_processing_db
spring.datasource.username=gondasatishkumar
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect